// Discovery types and the pure host↔service matcher.
//
// This module is deliberately a dependency-free leaf: `src/fp2-browser.ts` (the
// mDNS implementation) imports from here, and the compiled output is loaded by
// the Config UI X server process, so nothing here may import `homebridge` or a
// network library at runtime.

/**
 * An FP2 as advertised over mDNS (`_hap._tcp.local`), carrying its pairing
 * identity (the HAP `id`, formatted `XX:XX:XX:XX:XX:XX`) and the advertised
 * port — important because HAP accessories advertise on ephemeral high ports,
 * so the port can NEVER be hard-coded; it has to come from mDNS or config.
 */
export interface DiscoveredFp2 {
  deviceId: string;
  address: string;
  port: number;
  /** mDNS instance name, e.g. `Presence-Sensor-FP2-6A5A`. Retained so a config
   *  `host` given as a bonjour name (the form config.schema.json recommends)
   *  still matches against the cache, and so the wizard can label the device. */
  name?: string;
  /** Every address the FP2 advertised. `address` is the one we chose to connect
   *  on (IPv4-preferred); this keeps the rest for matching a config `host` that
   *  was written as an IP. */
  allAddresses?: string[];
  /** Aqara hardware serial, e.g. `54EF44508EA8` — the device's MAC, and the
   *  "accessory ID" the Aqara app displays. Unlike the HAP `deviceId` (which is
   *  random and REGENERATED by a factory reset) this is stable for the life of
   *  the hardware, so it is what the pairing store keys on. Sourced from the
   *  `_Aqara-FP2._tcp` TXT record and joined to the HAP record by their shared
   *  `.local` hostname. Optional: a device whose Aqara record hasn't been seen
   *  yet still discovers and connects normally. */
  serial?: string;
  /** Numeric pairing-status flags. Bit 0 = "AccessoryNotPaired" (sf=1 means
   *  pair-setup is permitted; sf=0 means the device is already paired). */
  statusFlags: number;
  /** Numeric pairing-feature flags (HAP "ff").
   *  - bit 0 (1) = SupportsAppleAuthenticationCoprocessor (MFi)
   *  - bit 1 (2) = SupportsSoftwareAuthentication
   *  Aqara FP2 reports ff=2 (software auth only). Determines which pair
   *  method to use: PairSetup (method 0) for software auth, PairSetupWithAuth
   *  (method 1) for MFi coprocessor. */
  featureFlags: number;
  /** Convenience: true iff the FP2 can accept pair-setup right now. */
  availableToPair: boolean;
  model: string;
  configNumber: number;
}

export interface HapServiceUp {
  name?: string;
  address: string;
  allAddresses?: string[];
  port: number;
  id: string;
  md: string;
  sf: number;
  ff: number;
  'c#': number;
}

/**
 * Decide whether an mDNS-discovered HAP service matches a user's `host`
 * identifier. Exported and pure so it can be exhaustively unit-tested.
 *
 * Match precedence:
 *  1. Preferred HAP deviceId (from a stored pairing) — wins over everything
 *     so we follow the FP2 across DHCP lease changes.
 *  2. IP equality against `svc.address` or any `svc.allAddresses`.
 *  3. mDNS bonjour name equality (with or without trailing dot).
 *  4. `.local` hostname containment when the target ends in `.local`.
 *
 * `host` and `preferredDeviceId` may both be omitted, in which case nothing
 * matches.
 */
export function matchesService(svc: HapServiceUp, host: string, preferredDeviceId?: string | null): boolean {
  if (preferredDeviceId) {
    const want = normalizeDeviceId(preferredDeviceId)?.toLowerCase();
    if (want && svc.id?.toLowerCase() === want) return true;
  }
  const targetLower = host.toLowerCase();
  const addresses = new Set(
    [svc.address?.toLowerCase(), ...(svc.allAddresses ?? []).map(a => a.toLowerCase())].filter(Boolean) as string[]
  );
  if (addresses.has(targetLower)) return true;
  const nameLower = (svc.name ?? '').toLowerCase();
  if (nameLower && (nameLower === targetLower || nameLower.replace(/\.$/, '') === targetLower.replace(/\.$/, ''))) {
    return true;
  }
  if (targetLower.endsWith('.local') || targetLower.endsWith('.local.')) {
    const stripped = targetLower.replace(/\.$/, '').replace(/\.local$/, '');
    if (nameLower.includes(stripped)) return true;
  }
  return false;
}

// `normalizeDeviceId` lives in mappers.ts (leaf module) so pairing-store can use
// it without circular deps; re-exported here for callers that import it from the
// discovery surface area.
export { normalizeDeviceId } from './mappers.js';
import { normalizeDeviceId } from './mappers.js';
