import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { normalizeDeviceId } from './mappers.js';
import type { StoredPairing } from './types.js';

/**
 * On-disk storage for HAP pairing data. One JSON file per FP2.
 *
 * Records are keyed by the Aqara hardware **serial** (`54EF44508EA8.json`) —
 * the only identifier that is stable for the life of the device. The HAP
 * deviceId is regenerated by a factory reset, and the IP/host changes with DHCP;
 * keying on either strands the pairing.
 *
 * Older versions keyed files by host/IP (`192.168.1.242.json`) and wrote no
 * serial. Those records still load via {@link findByDeviceId}, and are re-keyed
 * onto the serial by {@link save} on the next successful connect.
 *
 * Files live under {storagePath}/homebridge-fp2/{key}.json.
 */
export class PairingStore {
  constructor(private readonly baseDir: string) {}

  /** Sanitize any identifier (serial, host, IP) into a safe filename. */
  private fileFor(key: string): string {
    const safe = key.replace(/[^a-zA-Z0-9._-]/g, '_');
    return join(this.baseDir, `${safe}.json`);
  }

  /**
   * Look a pairing up by the stable hardware serial — the preferred path.
   * Falls back to scanning, since a record written by an older version is keyed
   * by host but may still carry the serial once re-saved.
   */
  async findBySerial(serial: string): Promise<StoredPairing | null> {
    const want = serial.trim().toLowerCase();
    if (!want) return null;
    const direct = await this.load(serial);
    if (direct) return direct;
    for (const record of await this.listAll()) {
      if (record.serial?.trim().toLowerCase() === want) return record;
    }
    return null;
  }

  async load(host: string): Promise<StoredPairing | null> {
    try {
      const raw = await readFile(this.fileFor(host), 'utf8');
      return JSON.parse(raw) as StoredPairing;
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw err;
    }
  }

  /**
   * Fallback lookup when `load(host)` misses — usually because the user
   * changed `host` in config (e.g. moved from IP to mDNS name, or vice
   * versa, or DHCP renamed the device's hostname). Scans every pairing
   * file in the store and returns the one whose deviceId matches.
   *
   * Returns null if nothing matches, or if the store directory is empty
   * / does not yet exist.
   */
  async findByDeviceId(deviceId: string): Promise<StoredPairing | null> {
    const { readdir } = await import('node:fs/promises');
    let entries: string[];
    try {
      entries = await readdir(this.baseDir);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw err;
    }
    // Normalize both sides so the hex-encoded ASCII form hap-controller
    // emits ("33343a38463a...") matches the canonical mDNS form
    // ("34:8F:C1:..."). Without this, the lookup silently misses.
    const want = normalizeDeviceId(deviceId)?.toLowerCase();
    if (!want) return null;
    for (const entry of entries) {
      if (!entry.endsWith('.json')) continue;
      try {
        const raw = await readFile(join(this.baseDir, entry), 'utf8');
        const record = JSON.parse(raw) as StoredPairing;
        const have = normalizeDeviceId(record.deviceId)?.toLowerCase();
        if (have === want) return record;
      } catch {
        // Skip unreadable / unparseable files — don't let one corrupt
        // pairing block recovery of others.
        continue;
      }
    }
    return null;
  }

  /**
   * Return every stored pairing in the store. Used by the setup wizard to tell
   * which discovered FP2s this plugin has already paired (so it can offer
   * "Configure" rather than a doomed re-pair). Skips unreadable / unparseable
   * files rather than failing the whole listing.
   */
  async listAll(): Promise<StoredPairing[]> {
    const { readdir } = await import('node:fs/promises');
    let entries: string[];
    try {
      entries = await readdir(this.baseDir);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return [];
      throw err;
    }
    const records: StoredPairing[] = [];
    for (const entry of entries) {
      if (!entry.endsWith('.json')) continue;
      try {
        const raw = await readFile(join(this.baseDir, entry), 'utf8');
        records.push(JSON.parse(raw) as StoredPairing);
      } catch {
        continue;
      }
    }
    return records;
  }

  /** The filename key for a record: the stable serial when we know it, else the
   *  host (legacy behaviour, for a device whose Aqara record hasn't been seen). */
  keyFor(record: Pick<StoredPairing, 'serial' | 'host'>): string {
    return record.serial?.trim() || record.host;
  }

  /**
   * Find a record saved under any of the addresses an FP2 currently advertises.
   *
   * This is the last-resort lookup for a **legacy** record: older versions keyed
   * files by the resolved IP and stored no serial, so neither `findBySerial` nor
   * (if the device was since factory-reset, changing its HAP id) `findByDeviceId`
   * can match it. Without this, such a record is invisible — the plugin would
   * conclude it holds no pairing at all and misreport a reset device as "claimed
   * by another controller".
   */
  async findByAddresses(addresses: readonly string[]): Promise<StoredPairing | null> {
    for (const address of addresses) {
      if (!address) continue;
      const record = await this.load(address);
      if (record) return record;
    }
    return null;
  }

  async save(record: StoredPairing): Promise<void> {
    const file = this.fileFor(this.keyFor(record));
    await mkdir(dirname(file), { recursive: true });
    // Write-then-rename so a crash mid-write can't corrupt an existing
    // pairing — losing it would force a factory reset of the FP2.
    const tmp = `${file}.tmp`;
    await writeFile(tmp, JSON.stringify(record, null, 2), { mode: 0o600 });
    await rename(tmp, file);
  }

  async clear(host: string): Promise<void> {
    const { rm } = await import('node:fs/promises');
    try {
      await rm(this.fileFor(host));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
    }
  }
}
